// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexo.WorkModel.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nexo.WorkModel.Infrastructure.Migrations
{
    [DbContext(typeof(WorkModelDbContext))]
    partial class WorkModelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("work")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nexo.BuildingBlocks.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOn")
                        .HasDatabaseName("ix_work_outbox_processed_on");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_work_outbox_tenant_id");

                    b.ToTable("outbox_messages", "work");
                });

            modelBuilder.Entity("Nexo.WorkModel.Domain.Process", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_version_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("EvidencePolicy")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("evidence_policy");

                    b.Property<string>("ExternalRef")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_ref");

                    b.Property<Guid?>("LineId")
                        .HasColumnType("uuid")
                        .HasColumnName("line_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OutputItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("output_item_id");

                    b.Property<Guid?>("OutputUomId")
                        .HasColumnType("uuid")
                        .HasColumnName("output_uom_id");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("profile");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("SkipPolicy")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("skip_policy");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_processes_code")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("Profile")
                        .HasDatabaseName("ix_processes_profile")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("processes", "work");
                });

            modelBuilder.Entity("Nexo.WorkModel.Domain.ProcessVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("change_reason");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("profile");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset?>("SuspendedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<short>("VersionMajor")
                        .HasColumnType("smallint")
                        .HasColumnName("version_major");

                    b.Property<short>("VersionMinor")
                        .HasColumnType("smallint")
                        .HasColumnName("version_minor");

                    b.Property<string>("VersionNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("version_no");

                    b.Property<short>("VersionPatch")
                        .HasColumnType("smallint")
                        .HasColumnName("version_patch");

                    b.Property<decimal?>("WorkloadSeconds")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("workload_sec");

                    b.HasKey("Id");

                    b.HasIndex("ProcessId")
                        .IsUnique()
                        .HasDatabaseName("ux_process_versions_published")
                        .HasFilter("state = 'published' AND deleted_at IS NULL");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_process_versions_state")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("ProcessId", "VersionNo")
                        .IsUnique()
                        .HasDatabaseName("ux_process_versions_no")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("process_versions", "work");
                });

            modelBuilder.Entity("Nexo.WorkModel.Domain.TaskDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<int>("LagSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("lag_sec");

                    b.Property<Guid>("PredecessorTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("predecessor_task_id");

                    b.Property<Guid>("ProcessVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_version_id");

                    b.Property<Guid>("SuccessorTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("successor_task_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("PredecessorTaskId")
                        .HasDatabaseName("ix_task_dep_predecessor");

                    b.HasIndex("SuccessorTaskId")
                        .HasDatabaseName("ix_task_dep_successor");

                    b.HasIndex("ProcessVersionId", "PredecessorTaskId", "SuccessorTaskId")
                        .IsUnique()
                        .HasDatabaseName("ux_task_dep_edge")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("task_dependencies", "work");
                });

            modelBuilder.Entity("Nexo.WorkModel.Domain.TaskInput", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Basis")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("basis");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsBlocking")
                        .HasColumnType("boolean")
                        .HasColumnName("is_blocking");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<Guid>("ProcessVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_version_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<bool>("RequiresTraceability")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_traceability");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<decimal?>("TolerancePct")
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("tolerance_pct");

                    b.Property<Guid>("UomId")
                        .HasColumnType("uuid")
                        .HasColumnName("uom_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_task_inputs_item_id");

                    b.HasIndex("TaskId", "ItemId")
                        .IsUnique()
                        .HasDatabaseName("ux_task_inputs_task_item")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("task_inputs", "work");
                });

            modelBuilder.Entity("Nexo.WorkModel.Domain.WorkTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Completion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("completion");

                    b.Property<string>("CompletionSpec")
                        .HasColumnType("jsonb")
                        .HasColumnName("completion_spec");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<int>("DisplaySeq")
                        .HasColumnType("integer")
                        .HasColumnName("display_seq");

                    b.Property<decimal?>("EstimatedDurationSeconds")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("estimated_duration_sec");

                    b.Property<string>("EvidencePolicyOverride")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("evidence_policy");

                    b.Property<string>("Instructions")
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<bool>("IsMilestone")
                        .HasColumnType("boolean")
                        .HasColumnName("is_milestone");

                    b.Property<bool>("IsParallelizable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_parallelizable");

                    b.Property<bool>("IsRepeatable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_repeatable");

                    b.Property<short>("MinEvidenceCount")
                        .HasColumnType("smallint")
                        .HasColumnName("min_evidence_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Obligation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("obligation");

                    b.Property<Guid>("ProcessVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_version_id");

                    b.Property<decimal?>("ProgressWeight")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("progress_weight");

                    b.Property<string>("RequiredAssetType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("required_asset_type");

                    b.Property<string>("RequiredCapability")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("required_capability");

                    b.Property<string>("RequiredEvidenceKind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("required_evidence_kind");

                    b.Property<Guid>("ResponsibleRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsible_role_id");

                    b.Property<decimal?>("StandardDurationSeconds")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("standard_duration_sec");

                    b.Property<Guid?>("SuggestedPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("suggested_person_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("ResponsibleRoleId")
                        .HasDatabaseName("ix_tasks_responsible_role_id")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("ProcessVersionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_tasks_version_code")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("tasks", "work");
                });

            modelBuilder.Entity("Nexo.WorkModel.Domain.ProcessVersion", b =>
                {
                    b.HasOne("Nexo.WorkModel.Domain.Process", null)
                        .WithMany()
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_process_versions_process");
                });

            modelBuilder.Entity("Nexo.WorkModel.Domain.TaskDependency", b =>
                {
                    b.HasOne("Nexo.WorkModel.Domain.ProcessVersion", null)
                        .WithMany("Dependencies")
                        .HasForeignKey("ProcessVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_dep_version");
                });

            modelBuilder.Entity("Nexo.WorkModel.Domain.TaskInput", b =>
                {
                    b.HasOne("Nexo.WorkModel.Domain.WorkTask", null)
                        .WithMany("Inputs")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_inputs_task");
                });

            modelBuilder.Entity("Nexo.WorkModel.Domain.WorkTask", b =>
                {
                    b.HasOne("Nexo.WorkModel.Domain.ProcessVersion", null)
                        .WithMany("Tasks")
                        .HasForeignKey("ProcessVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_version");
                });

            modelBuilder.Entity("Nexo.WorkModel.Domain.ProcessVersion", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Nexo.WorkModel.Domain.WorkTask", b =>
                {
                    b.Navigation("Inputs");
                });
#pragma warning restore 612, 618
        }
    }
}
