// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexo.Execution.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nexo.Execution.Infrastructure.Migrations
{
    [DbContext(typeof(ExecutionDbContext))]
    partial class ExecutionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("execution")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nexo.BuildingBlocks.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOn")
                        .HasDatabaseName("ix_execution_outbox_processed_on");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_execution_outbox_tenant_id");

                    b.ToTable("outbox_messages", "execution");
                });

            modelBuilder.Entity("Nexo.Execution.Domain.Evidence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Caption")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("caption");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<Guid?>("CapturedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("captured_by");

                    b.Property<byte[]>("ContentHash")
                        .HasColumnType("bytea")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_id");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<string>("HashAlgo")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("hash_algo");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean")
                        .HasColumnName("is_mandatory");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("evidence_kind");

                    b.Property<string>("MediaRef")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("media_ref");

                    b.Property<Guid?>("RequirementId")
                        .HasColumnType("uuid")
                        .HasColumnName("requirement_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TaskRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_run_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_ev_time");

                    b.HasIndex("ExecutionId")
                        .HasDatabaseName("ix_ev_exec");

                    b.HasIndex("FileId")
                        .IsUnique()
                        .HasDatabaseName("ux_ev_file")
                        .HasFilter("file_id IS NOT NULL AND deleted_at IS NULL");

                    b.HasIndex("RequirementId")
                        .HasDatabaseName("ix_ev_req");

                    b.HasIndex("TaskRunId")
                        .HasDatabaseName("ix_ev_run");

                    b.ToTable("evidence", "execution");
                });

            modelBuilder.Entity("Nexo.Execution.Domain.Execution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptanceAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acceptance_at");

                    b.Property<DateTimeOffset?>("ActualEndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_end_at");

                    b.Property<DateTimeOffset?>("ActualStartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_start_at");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_id");

                    b.Property<string>("CloseKind")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("close_kind");

                    b.Property<string>("CloseReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("close_reason");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset?>("CommittedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("committed_date");

                    b.Property<string>("ContractRef")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("contract_ref");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Deliverable")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("deliverable");

                    b.Property<Guid?>("DeliverableItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("deliverable_item_id");

                    b.Property<string>("Flavor")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("flavor");

                    b.Property<decimal>("GoodQuantity")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("good_qty");

                    b.Property<Guid?>("LineId")
                        .HasColumnType("uuid")
                        .HasColumnName("line_id");

                    b.Property<Guid?>("OwnerPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_person_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id");

                    b.Property<Guid>("ProcessVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_version_id");

                    b.Property<string>("ProgressMethod")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("progress_method");

                    b.Property<decimal>("ProgressPct")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("progress_pct");

                    b.Property<decimal>("RejectQuantity")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("reject_qty");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TargetItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_item_id");

                    b.Property<decimal?>("TargetQuantity")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("target_qty");

                    b.Property<Guid?>("TargetUomId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_uom_id");

                    b.Property<string>("TriggerExternalRef")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("trigger_external_ref");

                    b.Property<string>("TriggerKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("trigger_kind");

                    b.Property<Guid?>("TriggerRefId")
                        .HasColumnType("uuid")
                        .HasColumnName("trigger_ref_id");

                    b.Property<string>("TriggerRefKind")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trigger_ref_kind");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("VersionNo")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("version_no");

                    b.Property<Guid?>("WorkCenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_center_id");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_exec_code")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("CommittedDate")
                        .HasDatabaseName("ix_exec_committed")
                        .HasFilter("flavor = 'project' AND deleted_at IS NULL");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_exec_customer")
                        .HasFilter("customer_id IS NOT NULL");

                    b.HasIndex("ProcessVersionId")
                        .HasDatabaseName("ix_exec_version");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_exec_status")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("Flavor", "Status")
                        .HasDatabaseName("ix_exec_flavor_status")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("TriggerRefKind", "TriggerRefId")
                        .HasDatabaseName("ix_exec_trigger");

                    b.ToTable("executions", "execution");
                });

            modelBuilder.Entity("Nexo.Execution.Domain.InputConsumption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("method");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<decimal?>("PlannedQuantity")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("planned_qty");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("qty");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid?>("SerialId")
                        .HasColumnType("uuid")
                        .HasColumnName("serial_id");

                    b.Property<Guid?>("TaskInputId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_input_id");

                    b.Property<Guid?>("TaskRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_run_id");

                    b.Property<Guid>("UomId")
                        .HasColumnType("uuid")
                        .HasColumnName("uom_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_ic_batch")
                        .HasFilter("batch_id IS NOT NULL");

                    b.HasIndex("ExecutionId")
                        .HasDatabaseName("ix_ic_exec");

                    b.HasIndex("TaskRunId")
                        .HasDatabaseName("ix_ic_run");

                    b.HasIndex("ItemId", "RecordedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_ic_item_time");

                    b.ToTable("input_consumptions", "execution");
                });

            modelBuilder.Entity("Nexo.Execution.Domain.TaskRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ActualClosingSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("actual_closing_sec");

                    b.Property<long>("ActualControlSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("actual_control_sec");

                    b.Property<DateTimeOffset?>("ActualEndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_end_at");

                    b.Property<long>("ActualExecSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("actual_exec_sec");

                    b.Property<long>("ActualSetupSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("actual_setup_sec");

                    b.Property<DateTimeOffset?>("ActualStartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_start_at");

                    b.Property<long>("ActualWaitSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("actual_wait_sec");

                    b.Property<Guid?>("AssignedPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_person_id");

                    b.Property<Guid?>("AssignedRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_role_id");

                    b.Property<string>("AssignmentMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("assignment_mode");

                    b.Property<DateTimeOffset?>("BlockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("blocked_at");

                    b.Property<Guid?>("BlockedReasonCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocked_reason_code_id");

                    b.Property<string>("CloseReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("close_reason");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<decimal?>("EstimatedDurationSeconds")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("est_duration_sec");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_id");

                    b.Property<bool>("IsAdHoc")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ad_hoc");

                    b.Property<bool>("IsForcedClose")
                        .HasColumnType("boolean")
                        .HasColumnName("is_forced_close");

                    b.Property<bool>("IsMilestone")
                        .HasColumnType("boolean")
                        .HasColumnName("is_milestone");

                    b.Property<bool>("IsOnCriticalPath")
                        .HasColumnType("boolean")
                        .HasColumnName("is_on_critical_path");

                    b.Property<DateTimeOffset?>("MilestoneCommittedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("milestone_committed_date");

                    b.Property<DateTimeOffset?>("MilestoneReachedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("milestone_reached_at");

                    b.Property<short>("MinEvidenceCount")
                        .HasColumnType("smallint")
                        .HasColumnName("min_evidence_count");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Obligation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("obligation");

                    b.Property<short>("Occurrence")
                        .HasColumnType("smallint")
                        .HasColumnName("occurrence");

                    b.Property<decimal?>("ProducedQuantity")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("produced_qty");

                    b.Property<string>("ProgressMethod")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("progress_method");

                    b.Property<decimal>("ProgressPct")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("progress_pct");

                    b.Property<decimal?>("ProgressWeight")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("progress_weight");

                    b.Property<string>("RequiredEvidenceKind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("required_evidence_kind");

                    b.Property<Guid?>("ShiftId")
                        .HasColumnType("uuid")
                        .HasColumnName("shift_id");

                    b.Property<string>("SkipReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("skip_reason");

                    b.Property<decimal?>("StandardDurationSeconds")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("std_duration_sec");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<decimal?>("TargetQuantity")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("target_qty");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid?>("WorkCenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_center_id");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionId")
                        .HasDatabaseName("ix_task_runs_exec");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_task_runs_status")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("AssignedPersonId", "Status")
                        .HasDatabaseName("ix_task_runs_person")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("ExecutionId", "MilestoneCommittedDate")
                        .HasDatabaseName("ix_task_runs_milestone")
                        .HasFilter("is_milestone");

                    b.HasIndex("WorkCenterId", "ActualStartAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_task_runs_wc_time");

                    b.HasIndex("ExecutionId", "TaskId", "Occurrence")
                        .IsUnique()
                        .HasDatabaseName("ux_task_runs_instance")
                        .HasFilter("deleted_at IS NULL AND task_id IS NOT NULL");

                    b.ToTable("task_runs", "execution");
                });

            modelBuilder.Entity("Nexo.Execution.Domain.Evidence", b =>
                {
                    b.HasOne("Nexo.Execution.Domain.Execution", null)
                        .WithMany("Evidence")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ev_exec");
                });

            modelBuilder.Entity("Nexo.Execution.Domain.InputConsumption", b =>
                {
                    b.HasOne("Nexo.Execution.Domain.Execution", null)
                        .WithMany("InputConsumptions")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ic_exec");
                });

            modelBuilder.Entity("Nexo.Execution.Domain.TaskRun", b =>
                {
                    b.HasOne("Nexo.Execution.Domain.Execution", null)
                        .WithMany("TaskRuns")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_runs_exec");

                    b.OwnsMany("Nexo.Execution.Domain.TaskRunPrecedence", "Precedences", b1 =>
                        {
                            b1.Property<Guid>("TaskRunId")
                                .HasColumnType("uuid")
                                .HasColumnName("task_run_id");

                            b1.Property<Guid>("PredecessorTaskId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("predecessor_task_id");

                            b1.Property<int>("LagSeconds")
                                .HasColumnType("integer")
                                .HasColumnName("lag_sec");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(4)
                                .HasColumnType("character varying(4)")
                                .HasColumnName("type");

                            b1.HasKey("TaskRunId", "PredecessorTaskId");

                            b1.ToTable("task_run_precedences", "execution");

                            b1.WithOwner()
                                .HasForeignKey("TaskRunId");
                        });

                    b.Navigation("Precedences");
                });

            modelBuilder.Entity("Nexo.Execution.Domain.Execution", b =>
                {
                    b.Navigation("Evidence");

                    b.Navigation("InputConsumptions");

                    b.Navigation("TaskRuns");
                });
#pragma warning restore 612, 618
        }
    }
}
